silinternational/ecs-deploy

ecs-deploy
=> Use jq's raw output instead of tr, fix regression with grep

README.md
Based on my own and @shsu's [comment](https://github.com/silinternational/ecs-deploy/issues/26) I took the liberty of creating this tiny PR for the `README.md`.
I am sure it'll help people save a few minutes now and then.
=> Add AWS IAM policy example

ecs-deploy
Proposal for avoiding errors when services being updated have desired-count  <= 0
More information available on https://github.com/silinternational/ecs-deploy/issues/7
=> Fixes issue https://github.com/silinternational/ecs-deploy/issues/7

ecs-deploy
It is very possible I could be missing a variable guard after turning on `set -u`, but this looked like all of them and it is working for me now.
=> fix image updating

Dockerfile, README.md, codeship-services.yml, codeship-steps.yml, docker-compose.yml, ecs-deploy, run-tests.sh, test.bats
- Fairly significant code restructuring to use functions so that unit testing could be implemented.
- Unit tests added to cover image name parsing and new task definition creation
- Updated Dockerfile to use Alpine, reducing resulting image size by approximately 200Mb. (From 291Mb to 94Mb).
- Connected with Codeship for automated execution of tests in Docker image
Due to the amount of changes going in here I'd like to request as many people test this version before I merge it in. Tagging all contributors here, but anyone else is invited to test as well. 
@hnryjms @reidab @gregwebs @rafaelfelix @kevinkarwaski @d-me-tree @steevel @johnallen3d @beeva-javiermartincaro @erickrawczyk @brycereitano @mirague @ligaz @tpett @asotirov @gerar2 @inakiabt @donaldpiret @timrc @diddeb @jepettoruti …
=> Add unit testing and move to Alpine

ecs-deploy
=> Keep "placementConstraints" from old task definition

ecs-deploy
Used the ideas from #66 but worked off the latest `develop` branch. This is working for me here, let me know how it works for you.
=> Support blue/green deployments (based on #66)

Dockerfile, README.md, codeship-services.yml, codeship-steps.yml, docker-compose.yml, ecs-deploy, run-tests.sh, test.bats
- Rewritten to support unit tests
- Documentation updates
- Add support for `placementConstraints`
- Fix deregistering old task definitions
- Convert Docker image to use Alpine instead of Ubuntu
- Add support to update only tags on all containers
- Add auto-rollback support when new task definition does not deploy successfully
=> Major release of new features

README.md, docker-compose.yml, ecs-deploy, test.bats
Like: registry.example.com/repo/image/name:0.1.1
=> Support multi level images

README.md
Small update with installation instruction
=> Update README.md with Installation instructions

README.md, ecs-deploy
=> Add --version flag

ecs-deploy
Adding option to assume-role in other account and do deploy under that credentionals
=> Adding assume-role

README.md, ecs-deploy
Thank you @timoguin for fixing incorrect docs
=> 3.5.1 - Fix docs

README.md, ecs-deploy, test.bats
This release incorporates a few PRs, special thanks to the contributors:
- @kakakakakku for updating Alpine to 3.8
- @bobdoah for help with unbound variables
- @taka011239 for better Fargate support
- @yu-orz for adding executionRoleArn support
=> Release 3.7.0 - Upgrade Alpine, support executionRoleArn, fix unbound variable errors

ecs-deploy, test.bats
@fillup - ran all tests, seems to be working fine
Added two tests
- `ok 32 # skip (0) test createNewTaskDefJson with single container in definition and different repository`
- `ok 33 # skip (0) test createNewTaskDefJson with multiple containers in definition and different repository`
Closes #162
=> Replace image name, even if repository was changed - tested

Dockerfile, README.md, ecs-deploy
Includes #208 , thanks @unfor19!
=> Release 3.9.0 - Allow change/replace repo for an image in task definition

.gitignore, Dockerfile, README.md, ecs-deploy
Merged several PRs, thanks to @alexmckinnon (#217), @inokappa (#215), and @pchien (#220)!
To be released as `3.10.0`
=> Copy tags to new definition, platform version support for run-task, task def file fix, update Alpine

Dockerfile, README.md, ecs-deploy
- Fix GitHub Actions integration to support `--tag-only` parameter
- Fix GitHub Actions integration to support `--aws-assume-role` parameter
=> Release 3.10.1

action.yml, ecs-deploy
- Fix GitHub Actions integration to properly support `--force-new-deployment`
=> Release 3.10.2

ecs-deploy
Wait to see if more than 1 deployment stays running
=> fix: number of green deployments check

README.md, ecs-deploy
- Fix "successful deployment" check to be >= 1, not just == 1
- Add note to readme about ecs-deploy being "feature complete"
=> Release 3.10.3

ecs-deploy
- Correct the version number (forgot to update in previous release)
=> Release 3.10.4

ecs-deploy
This pull request fixes a bug of the healthcheck feature added in #200. It's also related to Issue https://github.com/silinternational/ecs-deploy/issues/187.
=> Fix: Service Deployment resulting as successful when encountering UNHEALTHY tasks.

README.md, ecs-deploy
- Fix order of `--force-new-deployment` and `--enable-rollback` (in relation to `-n` and `-d`) for GitHub Actions.
- Fix `HEALTHY` grep check to avoid matching `UNHEALTHY` when checking for successful deployment.
=> Release 3.10.5

ecs-deploy
=> #260 ecs deploy should wait for deployment

ecs-deploy
=> Release 3.10.6

action.yml
This PR should solve the #268 and #269 issues.
=> Fix gha run-task argument and add wait-for-success

ecs-deploy
- Update version number in ecs-deploy script file
- (From [previous, unpublished release](https://github.com/silinternational/ecs-deploy/pull/281):) Preserve ephemeral storage configuration in task definition
=> Release 3.10.13

ecs-deploy
- Add support for `--copy-task-definition-tags` in GitHub Actions
=> Release 3.11.0 - Support copying of tags in Github Action

.github/workflows/ci.yml, action-services.yml
- Update `docker-compose` to `docker compose`
- Remove version from action-services.yml file
=> update docker-compose to docker compose

.github/workflows/ci.yml, ecs-deploy
- Added branch name to tag list to address GHCR error
---
=> Release 3.10.21 - Fixed GHCR image push

README.md
- Revised the recommended IAM policy to limit access
=> revise the recommended IAM policy to limit access
