README.md, ecs-deploy
We want to specify the tag value via an environment variable. This adds the argument -e to provide the name of the env var and ecs-deploy will eval it to get the value for use as the tag value. This is useful in environments where env vars are available but you're not able to expand variables to values in the call to ecs-deploy.
=> Added support for specifying env var name to get tag value from

ecs-deploy
I ran into an issue of `./ecs-deploy: line 246: [: too many arguments` coming up. It looks like it was having some issues if there were multiple "Success" messages in results.
=> Fix too many arguments to if statement.

Dockerfile
While working on another pull request I found myself wanting to make changes, build and test them without committing and pushing to Github first. Is there any reason not to copy over the script directly from the source code?
=> Use Script from Local Path

README.md, ecs-deploy
Hi there! 
We are using delegated IAM roles in order to deploy our containers into different AWS accounts, so I added an aws profile selection from cli, so access key or secret key were retrieved from the [profile_name] section of ~/.aws/credentials (or $AWS_PROFILE, as shown in AWS credentials chain documentation).
Moreover, I fixed the use for the region parameter, as before it wasn't working for us.
I hope this helps someone, thanks for the great code!
=> AWS profiles and fix region support

ecs-deploy
It's possible for a task definition to have more than one container (ie. web and redis). If so the existing script will swap out both for the new image name. 
For example I had a task definition that looked something like this:
```json
{
"status": "ACTIVE",
"family": "bot",
"containerDefinitions": [
{
"name": "bot",
"image": "technekes/bot:cc3813d066893fd6c4"
},
{
"name": "redis",
"image": "redis:latest"
}
]
}
```
When I ran a deploy the script found both instances of `image` and replaced the value with the new image name/tag. I ended up with something like this:
```json
{
"status": "ACTIVE",
"family": "bot",
"containerDefinitions": [
{
"name": "bot",
"image": "technekes/bot:40495fa26f0bbc5d02"
},
{
"name": "redis",
"image": "technekes/bot:40495fa26f0bbc5d02"
}
]
}
```
I've attempted to …
=> Use Image Name When Updating Task Definition

ecs-deploy
ecs-deploy don't work if aws cli already configured with non json output. This fix it.
=> force json output for aws cli command

ecs-deploy
The existing implementation worked in GNU `sed` on Linux, but was failing on Mac OS X's BSD `sed`. This invocation works on both `sed`s.
=> Update `sed` usage for compatibility

README.md, ecs-deploy
Exposes the minimumHealthyPercent / maximumPercent service deployment options discussed here:
https://aws.amazon.com/blogs/compute/amazon-ecs-launches-new-deployment-capabilities-cloudwatch-metrics-singapore-and-frankfurt-regions/
=> Exposed min/max healthy percentage service deployment options.

ecs-deploy
I'm really glad to see these options exposed in this tool, but I think setting default values for them is a mistake. These values are persisted as part of the service record, not just used per-deploy. For anyone (like me) who had set these values in the AWS console, running ecs-deploy without --min and --max will reset them back to 100/200 and potentially cause deploys to fail.
/cc: @kevinkarwaski
=> Remove default values for --min and --max

ecs-deploy
I have a number of task definitions that I use to run one-off tasks like database migrations. When my CI server builds a new image, I need to update those services to reference the newly-built image tag.
This extends ecs-deploy to take either `--service-name` or `--task-definition` arguments. When given a task definition, all of same TD update logic applies, but the service-related updates are skipped.
=> Add support for updating task definitions directly

ecs-deploy
In commit d58e426d6233534d12cbd07332162d663303d714 `set -e` was added in order for
the script to exit on errors since it would just continue trying to do things
otherwise. This didn't play well with `grep` that returns exit code 1 when it
doesn't match.
=> Fix regression in d58e426d6233534d12cbd07332162d663303d714

ecs-deploy
This PR enables the usage of underscores in the username, image or tags fields in the -i parameter.
=> Allow underscores in username, image and tag

ecs-deploy
Prevent the rewrite of the task definition to update more than just the container you're updating the image for, if you have more than one container with the same name prefix.
eg.
servicename
servicename-web
=> Fix for the task definition rewrite sed command.

README.md
This PR adds the `---aws-instance-profile` argument and description to the README. 
After struggling to configure my awscli creds in an automated EC2 instance, I found issue #31 and thought it would save others a lot of time if it was prominently documented
=> add --aws-instance-profile to readme

ecs-deploy
This is a quick change to support AWS credentials file.
If AWS credentials are already saved in `~/.aws/credentials` ([doc](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files)) *aws-cli* doesn't require `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables.
=> Add AWS credentials file support

README.md
I realized I accidentally duplicated `--profile`'s short argument for `--aws-instance-profile` in PR #50 
This PR just removes the incorrect `-p` option from `--aws-instance-profile`. My bad!
=> Remove incorrect short argument for --aws-instance-profile

ecs-deploy
This is perhaps specific to my setup. However, breaking up pipes when they are small is a technique towards producing better error messages (you can check intermediate states) so I think this is still a good change overall.
I run the `aws` command from a docker container with `-it` set.
This causes the error
cannot enable tty mode on non tty input
Also quote some variables
=> avoid piping to the aws command

README.md, ecs-deploy
Adding the ability to deregister the old task definition when the new one has been deployed successfully will clear some of the clutter in the AWS Management Console, as the configurations would otherwise build up indefinitely.
=> Deregister Outdated ECS Task Definition

README.md, ecs-deploy
./ecs-deploy -p default -c Cluster -n Service -i image:tag -m 50 -M 200 -t 300 -D 4
The `-D 4` will set the desired-count to 4 while updating service.
=> Adding support for --desired-count parameter on update-service

ecs-deploy
This is causing an error when the variable is not defined (i.e. argument not being passed in).
=> Resolved Undefined $DESIRED Variable

README.md, ecs-deploy
Does anyone have objections to this being merged into master and tagged as a new release? I'll wait a day or two to merge it in.
=> Support for deregistering old task definitions and setting desired count of tasks for service

ecs-deploy
This commit adds support for the newly introduced network mode in ECS. 
The solution requires the IF statement because ECS task definitions with network mode "bridge" will not print the networkMode attribute to the JSON output, whereas task definitions with network mode "host" will.
=> Added networkMode option for task definitions

ecs-deploy
I may have introduced this problem in my last PR, there is a spurious API call (failure is ignored, but seeing it is annoying).
=> only call describe-tasks when there is data

ecs-deploy
@statusfailed, @triplesec, @seanadkinson, @EverydayPineapple
I added some new conditional logic to build up the jq filter for creating the new task definition based on the presence of given options, specifically `networkMode` and `taskRoleArn`. From my testing this is working properly but would you mind checking it too before I merge it in?
=> Support for conditional options like networkMode and taskRoleArn

ecs-deploy
If repo is empty do not add a trailing slash
=> Fix #70 Double slash in image name

ecs-deploy
This reverts commit cc75ef18a1fbaf595476c97e3ef0720d20c5f336.
Git got confused about this revert, but it seemed straightforward enough to me.
Warning: this is untested. It is difficult for me to properly test since the old version didn't work right for me.
=> Revert "update the image with jq, not sed"

ecs-deploy
Amazon ECR allows dots in the names of repositories, but this script
does not. Just updating the regex to be more permissive.
=> Allow dots in image names

ecs-deploy
By passing in the filter to `jq '.taskDefinition'` the `taskRoleArn` values are lost. The filter seems to be a legacy artifact, as the code-block underneath already checks for both `networkMode` and `taskRoleArn` and includes them in the new task definition when present in the old one.
Addresses issue #76.
=> Fix missing `taskRoleArn` parameter in new defintion

README.md
It looks like the `iam:PassRole` permission is also required for creating tasks.
=> Add iam:PassRole to example IAM Policy

docker-compose.yml, ecs-deploy, test.bats
This PR incorporates the changes from #79 after the refactoring for unit tests. 
@bknoth I did my best to bring your code in although after i refactored it all it was a little complicated. I believe it is all working though as I added a couple unit tests for it as well. Can you check this out and ensure it works the way you originally intended?
=> add tagonly support and unit tests for it

ecs-deploy
Hi !
I found a typo `--task-definiton` when I tried using ecs-deploy.
> $ ./ecs-deploy -c my-cluster
One of SERVICE or TASK DEFINITON is required. You can pass the value using -n / --service-name for a service, or -d / --task-definiton for a task
Thanks 👍
=> Fixed typo

ecs-deploy
If you have specified placement constraints in your task definition (i.e. only deploy these to this instance), they won't get included when the task generation gets regenerated, for a new deployment. This includes them.
=> Include placementConstraints when regenerating task definition

ecs-deploy, test.bats
AWS released new service "AWS Fargate" on November 30, 2017.
- https://aws.amazon.com/fargate/
This Pull Request goal is supporting AWS Fargate deployment, and solve this Issue ( https://github.com/silinternational/ecs-deploy/issues/127 ).
This error occurred by latest ecs-deploy.
```
An error occurred (InvalidParameterException) when calling the UpdateService operation: Task definition does not support launch_type FARGATE.
```
Because `Launch Types` ( parameter name is `requiresCompatibilities` ) added on Task Definition.
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
Then `requiresCompatibilities` set value `FARGATE` or `EC2`, but `EC2` is default ECS.
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html
If you …
=> Supported AWS Fargate

ecs-deploy
Fixes https://github.com/silinternational/ecs-deploy/issues/115 where the script would exit with `TASK_DEFINITION_ARN: unbound variable`. Also fixes another bug down the line where a task definition is expected during `createNewTaskDefJson()` but all we have is a task definition name.
=> fix task-definition only update bug, #115

README.md, ecs-deploy, test.bats
- https://github.com/silinternational/ecs-deploy/issues/137
In February, ECS supported new option `--force-new-deployment`.
We can use this option to deploy with no service definition changes ( = force ) .
- https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html
I supported `--force-new-deployment` for ecs-deploy.
It works with my ECS cluster 🎉 
```sh
$ ./ecs-deploy --cluster xxx --service-name yyy --force-new-deployment
Force a new deployment of the service
Waiting for service deployment to complete...
Service deployment successful.
```
```sh
$ docker-compose run --rm test
fetch http://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch …
```
=> Supported "--force-new-deployment" option

ecs-deploy, test.bats
Effect of turning echo $X into echo "$X" is that bash-expandable characters like `*` are not expanded anymore and that the formatting of `X` is persevered. Therefore, I changed to tests to compare with the help of `jq`.
Fixes #111
=> Avoid bash expansions

README.md, ecs-deploy
Some services takes a lot of time to drain old tasks, this may require waiting a lot for deploy to finish. In my case some times more than 5 minutes...
This optional parameter helps to finish deploy faster
=> Skip deployments check

README.md, ecs-deploy
Run created task now if set `run-task` option with `task-definition` .
```
ecs-deploy --cluster app --task-definition app-migration --image my-app:latest --run-task
```
=> add `run-task` option

README.md, ecs-deploy, test.bats
Merged in several PRs:
- #112 - Avoid Bash Expansions
- #118 - Update only task definition (without service)
- #141 - Add support for "force new deployment"
- #148 - Add "skip deployments check" to speed up deployment and not wait for deployment to finish before exiting
- #150 - Add `--run-task` option for running one off tasks (not ongoing service)
Big thanks to @fbenz, @eguven, @kakakakakku, @Kostanos, and @nazo for their contributions to this release.
=> Release 3.5.0

README.md, ecs-deploy
- This adds the option to use the *latest* task definition that has been created for the family; in
the previous implementation, the only option was to use the currently running task definition as a base.
There are scenarios where a task definition may be created, yet not deployed where this is useful.
This PR will keep the previous implementation as the default so this will not be a breaking change.
=> Add flag for using the latest task definition

README.md, ecs-deploy
Merged in #125 to add flag for using the latest task definition
`--use-latest-task-def         Will use the most recently created task definition as it's base, rather than the last used.`
=>  Add flag for using the latest task definition

ecs-deploy
If "executionRoleArn" is specified for Task, ecs-deploy will result in an error and a filter will be added because it failed.
```
An error occurred (ClientException) when calling the RegisterTaskDefinition operation: When you are specifying container secrets, you must also specify a value for 'executionRoleArn'.
```
=> add executionRoleArn into NEW_DEF_JQ_FILTER

Dockerfile, test.bats
Hi @fillup 😄 
Alpine Linux 3.5 is already NOT supported.
( End of Support : 2018-11-01 )
- https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
So, I updated to Alpine Linux 3.8 (latest).
- https://hub.docker.com/r/_/alpine/
Some tests are failed with Alpine Linux 3.8 because `[ ]` and `jq` syntax are NOT correct.
So, I fixed it together 👍 
```sh
$ docker-compose run --rm test
...
not ok 29 test createNewTaskDefJson with single container in definition
not ok 30 test createNewTaskDefJson with single container in definition for AWS Fargate
not ok 31 test createNewTaskDefJson with multiple containers in definition
ok 32 test parseImageName with tagonly option # skip 0
not ok 33 test createNewTaskDefJson with multiple containers in definition and replace only tags
```
```sh
$ …
```
=> Use Alpine Linux 3.8 on Dockerfile

ecs-deploy
After merging #173 the unit tests started failing. The addition of `+undefined-guard` to `port` in testing caused the addition of a colon to the repo name in an invalid position. After troubleshooting I found it was caused when the image name in use was a "root level" image and therefore several variables were not being defined/initialized, namely `domain`, `port`, and `repo`. Now I'm initializing them to an empty string so a simple test without the `undefined-guard` works properly.
All unit tests are now passing and manually running ecs-deploy with each kind of matching image name are working without throwing unbound variable errors as reported in #171. 
Further info on comparison method: https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash/13864829#138648 …
=> changing comparisons to avoid unbound errors and problems caused by undefined-guard

ecs-deploy
This was needed to be able to --run-task using --launch-type FARGATE and platform version 1.4.0 instead of LATEST which is 1.3.0
=> Allow --platform-version to be configured when using --run-task

README.md, ecs-deploy
This allows the option to copy the existing task definition tags over to new revisions created using `ecs-deploy` by including a `--copy-task-definition-tags` argument to the command. 
We recently came across this issue as the initial task definitions created via Terraform were being tagged but subsequent revisions created via the ecs-deploy script didn't have the original tags carried over.
I noticed there was an existing issue mentioning this as well. Posting a PR on how we added this functionality on our end in case this is helpful to others as this resolves https://github.com/silinternational/ecs-deploy/issues/212
=> Add --copy-task-definition-tags argument to copy task definition tags to new revisions

ecs-deploy
Hi
When we use `--task-definition-file`, the content of the file specified by the `--task-definition-file` option is not used,
because of the following situation.
```sh
if [ $TASK_DEFINITION_FILE == false ]; then
taskDefinition="$TASK_DEFINITION"
else
taskDefinition="$(cat $TASK_DEFINITION_FILE)"
fi
if [[ "x$TAGONLY" == "x" ]]; then
DEF=$( echo "$TASK_DEFINITION" \
| sed -e 's~"image":.*'"${imageWithoutTag}"'.*,~"image": "'"${useImage}"'",~g' \
| jq '.taskDefinition' )
```
Please confirm.
Yohei
=> Change variable $TASK_DEFINITION to $taskDefinition (`--task-definition-file` option not working)

action.yml
Adding support for `tag_only` in GitHub Actions
=> add tag_only support for GitHub actions

action.yml
It was missing the command input `force_new_deployment_cmd` so this PR adds it
```
Warning: Unexpected input(s) 'force_new_deployment_cmd', valid inputs are ['entryPoint', 'args', 'aws_access_key_cmd', 'aws_access_key', 'aws_secret_key_cmd', 'aws_secret_key', 'service_name_cmd', 'service_name', 'task_definition_cmd', 'task_definition', 'region_cmd', 'region', 'profile_cmd', 'profile', 'cluster_cmd', 'cluster', 'image_cmd', 'image', 'aws_assume_role', 'desired_count', 'min_cmd', 'min', 'max_cmd', 'max', 'timeout_cmd', 'timeout', 'tag_env_var', 'tag_only', 'max_definitions_cmd', 'max_definitions', 'enable_rollback_cmd', 'enable_rollback', 'use_latest_task_def_cmd', 'use_latest_task_def', 'force_new_deployment', 'run_task', 'skip_deployments_check_cmd', 'skip_deployments_check', 'verbose'] …
```
=> Fix missing gh action input for force-new-deployment

action.yml
if `--force-new-deployment` and/or `--enable-rollback` come before `-n` or `-d` then this script will fail.
in GitHub actions we have no control over argument order, so this places them after `-n`, `-d`
=> bug: github actions deploy fails if enable_rollback and force_new are not after -n, -d

ecs-deploy
ecs-deploy is overwriting runtimePlatform containing operatingSystemFamily and cpuArchitecture
=> add runtimePlatform to CONDITIONAL_OPTIONS

ecs-deploy
- Preserve value of `runtimePlatform` (containing operatingSystemFamily and cpuArchitecture)
=> Release 3.10.7

ecs-deploy
This small fix allows a smooth interaction with deploys of services that might have or not have tags.
All credit goes to @oliveirafilipe for providing the solution in this issue: https://github.com/silinternational/ecs-deploy/issues/232
I've tested the fix, with the argument in place, bot task definitions with and without tags are being deployed smoothly.
=> BUG: copy-task-definition-tags error when task def has no tags

action.yml
While reviewing PR #272 I noticed two other commands that were missing in the github actions input list.
=> add missing github actions inputs (desired_count_cmd, tag_env_var_cmd)

Dockerfile
In order to simplify the execution in a shell (such as in CI systems), the executable should be located in a standard UNIX `PATH` location. I picked `/usr/local/bin` in order to specify the executable is not coming from a standard package.
* link `/ecs-deploy` to the new location for compatibility in case some people are already using the image with this location of the script.
* remove some `RUN` command as the files are already executable in git, therefore the copy during the build will keep those `x` flags.
* minor typo in comment
It might be issue faced by the user in #124.
Currently, this fails:
```console
$ docker run -it --rm --entrypoint "" silintl/ecs-deploy:3.10.0 ecs-deploy --version
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting …
```
=> container: standard PATH location for the script

ecs-deploy
The `ecs-deploy` script is now located at `/usr/local/bin` in the Docker image, with a symlink at the original location (`/`).
_Note: this change was effective in 3.10.9 but the script self-reported version number was not updated in that version._
=> Release 3.10.10 - move the script into the PATH

ecs-deploy
The `ephemeralStorage` task definition parameter for Fargate tasks was not being preserved by ecs-deploy, causing unexpected disk space problems after deployments. This fixes that.
=> Preserve ephemeral storage configuration in task definition

.github/pull_request_template.md, ecs-deploy
- Fix version number in `ecs-deploy` script itself
- Add pull request (PR) template to help us remember this step in the future
---
=> Release 3.10.15 - Fix version number in script

ecs-deploy
Repository names may contain underscores, but they can't start with one.
=> Allow underscores in repository names.

.github/pull_request_template.md, docker-compose.yml, ecs-deploy, test.bats
- README and ecs-deploy no longer list silintl/mariadb as an example
- Fixed tag name regular expression to allow underscores.
---
=> Release 3.10.16 - allow underscores in tag names

ecs-deploy, test.bats
- Keep `proxyConfiguration`, if present
Fixes #236 
---
=> Keep `proxyConfiguration`, if present

.github/workflows/ci.yml, ecs-deploy
Added
-  version 3.10.19
- Pushing the Docker images to ghcr.io (Git Container Registry)   
=> Release 3.10.19 --GHCR.io image push

ecs-deploy, test.bats
`ecs-deploy` is in maintenance mode, but this change is backward-compatible and addresses a necessary use case by enabling support for container images with digests.
I would appreciate it if you could consider merging it.
- Support container image with digest.
- Add tests for container image with digest.
https://github.com/silinternational/ecs-deploy/issues/294
---
=> Add support for container image with digest

.github/workflows/ci.yml, ecs-deploy, test.bats
- Fixes #303 
When multiple images with similar names are used in the container definition, this will ensure only the specified one will be updated. 
---
=> Release 3.10.22 -- fix task definition creation with multiple similar images defined
